name: Update Blog Data
on: [push]

jobs:
  process-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required if blog-posts is a submodule

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Verify paths
        run: |
          echo "Repository contents:"
          ls -R
          echo -e "\nTools directory contents:"
          ls -lah tools/

      - name: Run scripts from root
        run: |
          python tools/alpha.py
          python tools/beta.py

      - name: Check output
        run: |
          echo "Generated files in blog-posts/:"
          find blog-posts -name "*.json" -exec ls -lah {} \;
          [ -f "blog-posts/meta.json" ] || exit 1  # Fail if no output

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add blog-posts/
          git diff --cached --quiet || (git commit -m "Auto-update blog data" && git push)