name: Run Python Scripts on Push

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ensure this version is compatible with your scripts

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests  # Install necessary dependencies

      - name: Run alpha.py and beta.py
        run: |
          python tools/alpha.py
          python tools/beta.py

      - name: Check if scripts ran successfully
        run: |
          echo "Checking if the scripts ran without issues..."
          # You can also include any checks you need to ensure scripts ran successfully
          # For example, checking for output files or logs.
