name: Auto-Update Blog Data
on:
  # AUTO-TRIGGERS (when these events occur):
  push:
    paths:
      - 'tools/**.py'          # When scripts change
      - 'blog-posts/**'        # When content changes
      - '.github/workflows/**' # When workflow changes
    branches: [ main ]
  
  # MANUAL CONTROL (optional):
  workflow_dispatch:           # "Run workflow" button in GitHub UI
  
  # SCHEDULED (optional - runs at 8AM UTC daily):
  schedule:
    - cron: '0 8 * * *'

jobs:
  process-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Run scripts
        run: |
          python tools/alpha.py
          python tools/beta.py
          
      - name: Commit changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add blog-posts/
          git diff --cached --quiet || (git commit -m "Auto-update: ${{ github.sha }}" && git push)