name: Execute Python Scripts
on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests  # Add all required packages here
          
      - name: Run scripts with error handling
        run: |
          echo "=== STARTING SCRIPTS ==="
          python tools/alpha.py || echo "Alpha failed"
          python tools/beta.py || echo "Beta failed"
          echo "=== SCRIPTS COMPLETED ==="
          
      - name: Verify Output
        run: |
          echo "Generated files:"
          find blog-posts -name "*.json" -exec ls -lah {} \;