name: Execute Python Scripts
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests

      - name: Run scripts
        run: |
          echo "=== STARTING SCRIPTS ==="
          python tools/alpha.py
          python tools/beta.py
          echo "=== SCRIPTS COMPLETED ==="

      - name: Verify output files
        run: |
          echo "Generated files:"
          find blog-posts -name "*.json" -exec ls -lah {} \;
          [ -f "blog-posts/meta.json" ] || exit 1
          [ -f "blog-posts/post1/images.json" ] || exit 1

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add blog-posts/
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update: Script-generated JSON files [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi