name: Execute Python Scripts
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run scripts
        run: |
          python tools/alpha.py
          python tools/beta.py
          python tools/gamma.py
          
      - name: Force commit all generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add blog-posts/
          git commit -m "Auto-update: Regenerate all files [skip ci]" --allow-empty
          git pull --rebase
          git push